version: '{build}'

branches:
  only:
    - main

image:
  - Ubuntu2004

install:
  - ps: git submodule update --init --recursive
  - pushd ~
  - svn checkout -r 3120 https://svn.code.sf.net/p/tass64/code/trunk tass64-code
  - cd ~/tass64-code && make -j$(nproc)
  - popd

build_script:
  - pushd submodules/acorn_mos_disassembly
  - make VERBOSE=1 "TASSCMD=$HOME/tass64-code/64tass"
  - popd
  - ps: $ver=Get-Content "submodules/acorn_mos_disassembly/build/refresh_version.dat"
  - ps: |
      $env:RELEASE_NAME="mos-6."+$ver+"-7."+$ver+"-8."+$ver
      $env:CI_ARCHIVE=$env:RELEASE_NAME+".zip"
      mv submodules/acorn_mos_disassembly/build/6xx ("6."+$ver)
      mv submodules/acorn_mos_disassembly/build/7xx ("7."+$ver)
      mv submodules/acorn_mos_disassembly/build/8xx ("8."+$ver)
      zip -9r $env:CI_ARCHIVE ("6."+$ver) ("7."+$ver) ("8."+$ver)
      zip -9j $env:CI_ARCHIVE "docs/README.txt"
  - env

artifacts:
  - path: $(CI_ARCHIVE)
    name: ci_archive
    
