version: '{build}'

branches:
  only:
    - main

image:
  - Ubuntu2004

install:
  - ps: git submodule update --init --recursive
  - pushd ~
  - svn checkout -r 3120 https://svn.code.sf.net/p/tass64/code/trunk tass64-code
  - cd ~/tass64-code && make -j$(nproc)
  - popd

build_script:
  - pushd submodules/acorn_mos_disassembly
  - make VERBOSE=1 "TASSCMD=$HOME/tass64-code/64tass"
  - popd
  - ps: $ver=Get-Content "submodules/acorn_mos_disassembly/build/refresh_version.dat"
  - ps: |
      $env:RELEASE_NAME="mos-refreshed-"+$ver
      $env:CI_ARCHIVE=$env:RELEASE_NAME+".zip"
      mv submodules/acorn_mos_disassembly/build/320r ("320"+$ver)
      mv submodules/acorn_mos_disassembly/build/350r ("350"+$ver)
      mv submodules/acorn_mos_disassembly/build/510r ("510"+$ver)
      zip -9r $env:CI_ARCHIVE ("320"+$ver) ("350"+$ver) ("510"+$ver)
      zip -9j $env:CI_ARCHIVE "docs/README.txt"
  - env

artifacts:
  - path: $(CI_ARCHIVE)
    name: ci_archive
    
deploy:
  - release: $(RELEASE_NAME)
    description: See https://github.com/tom-seddon/acorn_mos_disassembly/blob/master/docs/refresh.md
      
    provider: GitHub
    auth_token:
      secure: qT8fpG/5gPPir6BcMBaQAFgGfuiBd5+AP2vwiHM6bVHdvUOapT2sMgD16YvyHMO0
    artifact: ci_archive
    draft: false
    prerelease: false
